### ISSUE TITLE
Description and README.md missing period.

### ISSUE THREAD

**Issue by JonHypersomniac** [krasgo/LoungeBot#1]
The GitHub repo description and `README.md` says the following:

```
A Discord bot being made by two spectacular friends for some other spectacular friends
```

However it is missing a period (`.`) at the end. I believe this issue should get resolved by adding a period in both places.

**Comment by adamaniac987** [comment]
I have accordingly changed the `README.md` to include the period.  However, I do not have permission to edit the repository description—I will elevate the issue to the owner (@krasgo). Thank you for your contribution!

**Comment by krasgo** [comment]
k fixed lol

**Comment by JonHypersomniac** [comment]
It's a comma and not a period.

**Comment by krasgo** [comment]
oh shoot

**Comment by krasgo** [comment]
done
